---
apiVersion: v1
kind: Namespace
metadata:
  name: smartticket

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: smartticket
data:
  QUARKUS_OTEL_RESOURCE_ATTRIBUTES: service.namespace=smartticket_new
  QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.otel.svc.cluster.local:4317
  QUARKUS_LOG_CONSOLE_FORMAT: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled}] [%c{3.}] (%t) %s%e%n"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-rabbitmq
  name: order-rabbitmq
  namespace: smartticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-rabbitmq
  template:
    metadata:
      labels:
        app: order-rabbitmq
    spec:
      containers:
      - image: bfrevel/smartticket-order-rabbitmq:latest
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-rabbitmq
  name: order-rabbitmq
  namespace: smartticket
spec:
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: mgmt
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: order-rabbitmq
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: event-postgres
  name: event-postgres
  namespace: smartticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-postgres
  template:
    metadata:
      labels:
        app: event-postgres
    spec:
      containers:
      - image: postgres:16.1-alpine
        name: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: event-postgres
  name: event-postgres
  namespace: smartticket
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: event-postgres
  type: ClusterIP



---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: event-redis
  name: event-redis
  namespace: smartticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-redis
  template:
    metadata:
      labels:
        app: event-redis
    spec:
      containers:
      - image: redis:7.2.3-alpine
        name: redis
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: event-redis
  name: event-redis
  namespace: smartticket
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: event-redis
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: event-api
  name: event-api
  namespace: smartticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-api
  template:
    metadata:
      labels:
        app: event-api
    spec:
      containers:
      - image: bfrevel/smartticket-event-api:latest
        name: event-api
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: otel-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: event-api
  name: event-api
  namespace: smartticket
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: event-api
  type: ClusterIP




---
apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: order-api
  name: order-api
  namespace: smartticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - image: bfrevel/smartticket-order-api:latest
        name: order-api
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: otel-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-api
  name: order-api
  namespace: smartticket
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: order-api
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: order-processor
  name: order-processor
  namespace: smartticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
      - image: bfrevel/smartticket-order-processor:latest
        name: order-processor
        envFrom:
        - configMapRef:
            name: otel-config


---
apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: web
  name: web
  namespace: smartticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: bfrevel/smartticket-web
        name: web
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
  namespace: smartticket
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartticket-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  namespace: smartticket
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /()(.*)
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80
      - path: /event-api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: event-api
            port:
              number: 80
      - path: /order-api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: order-api
            port:
              number: 80